version: '3'

services:
  
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'

  server:
    build: scripts/server
    volumes:
      - ../scripts/server:/scripts
    ports:
      - 8090:8090
    depends_on:
      - rabbitmq
      
  worker:
    build: scripts/worker
    volumes:
      - ../scripts/worker:/scripts
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - server

  