version: '3'

services:
  
  database:
    image: 'mongo'
    container_name: 'database'
    restart: always
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - './init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js'
      - './mongo-volume:/data/db'
    networks:
      - backend
    environment:
      - MONGO_INITDB_DATABASE=collabse-db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor

  broker:
    image: 'rabbitmq:3.6-management-alpine'
    networks:
      - backend
    ports:
      - '5672:5672'
      - '15672:15672'
      
  db_handler:
    build: ../backend/db_handler
    volumes:
      - ../backend/db_handler:/scripts
    env_file:
      - config.env
    ports:
      - 8070:8070
    networks:
      - backend
    restart: always
    depends_on:
      - database
      - broker

  server:
    build: ../backend/server
    volumes:
      - ../backend/server:/scripts
    ports:
      - 8090:8090
    networks:
      - backend
    restart: always
    depends_on:
      - broker
      - db_handler
      
  worker:
    build: ../backend/worker
    volumes:
      - ../backend/worker:/scripts
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - backend
    restart: always
    depends_on:
      - server
      - db_handler
      - broker

  frontend:
    build: ../frontend
    volumes:
      - ../web:/web
    ports:
      - 8080:8080
    networks:
      - backend
    restart: always
    depends_on:
      - server

networks:
  backend:
    driver: bridge

  