name: Docker Image CI

on:
  push:
    branches: [ "yaroslav-dev" ]
  pull_request:
    branches: [ "yaroslav-dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose -f docker/docker-compose.yml up -d && bash tests.sh
